services:
  app:
    build: .
    container_name: my-admin-app
    restart: unless-stopped
    network_mode: host
    environment:
      - MONGODB_URI=mongodb://localhost:27017/my_admin
      - JWT_SECRET=615b2c65-1564-495b-9387-72fb0bacf832
      - JWT_EXPIRES_IN=24h
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs